apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs
  labels:
    app: docs
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: docs
  template:
    metadata:
      labels:
        app: docs
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: docs
          image: rg.fr-par.scw.cloud/crawly-app/docs:0.0.4
          imagePullPolicy: Always
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 10m
              memory: 50Mi
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: "production"